spring:
    application:
        name: push-notification-task

    jpa:
        show-sql: ${SHOW_SQL:true}
        properties:
            hibernate: {format_sql: true}

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3308}/${MYSQL_DB:task_notification}?useUnicode=yes&characterEncoding=UTF-8"
        username: ${MYSQL_USERNAME:test}
        password: ${MYSQL_PASSWORD:test}
        hikari:
            maximumPoolSize: ${MYSQL_POOL_MAX_CONNECTION:15}
            connectionTimeout: 60000

sms:
    config:
        numberOfSMSesPerMinute: ${NUMBER_OF_SMS:10}
        jobDurationInMinutes: ${SMS_JOB_DURATION_IN_MINUTES:0 0/1 * * * ?}

pushNotification:
    config:
        jobDurationInMinutes:  ${NOTIFICATION_JOB_DURATION_IN_MINUTES:0 0/2 * * * ?}